# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create a new KMedoids object.
#'
#' @return an external ptr (Rcpp::XPtr) to a KMedoids object instance.
.KMedoids__new <- function(k, max_iter, build_confidence, swap_confidence) {
    .Call('_BanditPAM_KMedoids__new', PACKAGE = 'BanditPAM', k, max_iter, build_confidence, swap_confidence)
}

#' Fit the KMedoids algorthm given the data and loss
#'
#' @param xp the km::KMedoids Object XPtr
#' @param data the data matrix
#' @param loss the loss indicator
.KMedoids__fit <- function(xp, data, loss) {
    invisible(.Call('_BanditPAM_KMedoids__fit', PACKAGE = 'BanditPAM', xp, data, loss))
}

#' Return the final medoids
#'
#' @param xp the km::KMedoids Object XPtr
.KMedoids__get_medoids_final <- function(xp) {
    .Call('_BanditPAM_KMedoids__get_medoids_final', PACKAGE = 'BanditPAM', xp)
}

